arm_name: KINOVA_GEN3_2_RIGHT

KINOVA_GEN3_2_RIGHT:
  gravitational_acceleration:
    - -9.7
    - 1.0
    - -1.3

  PRE_CONDITION:
    constraint_count: 2
    constraints:
      1:
        type: POSITION_XYZ
        value:
          - 0.5
          - 0.5
          - NULL
        operator:
          - GREATER_THAN
          - GREATER_THAN
          - NULL

      2:
        type: FORCE_XYZ
        value:
          - 0.5
          - 0.5
          - 0.5
        operator:
          - GREATER_THAN
          - GREATER_THAN
          - GREATER_THAN

  PER_CONDITION:
    constraint_count: 3
    constraints:
      1:
        type: POSITION_XYZ
        value:
          - 0.5
          - 0.5
          - 0.5
        operator: 
          - EQUAL
          - EQUAL
          - EQUAL

      2:
        type: VELOCITY_XYZ
        value:
          - 0.5
          - 0.5
          - 0.5        
        operator:
          - EQUAL
          - EQUAL
          - EQUAL

      3:
        type: FORCE_XYZ
        value:
          - 0.5
          - NULL
          - 0.5
        operator:
          - EQUAL
          - NULL
          - EQUAL

      4:
        type: ORIENTATION_QUATERNION
        value:
          - 0.5
          - 0.5
          - 0.5
          - 0.5
        operator:
          - EQUAL
          - EQUAL
          - EQUAL
          - EQUAL


  POST_CONDITION:
    constraint_count: 2
    constraints:
      1:
        type: FORCE_XYZ
        value:
          - 0.5
          - 0.5
          - 0.5
        operator:
          - EQUAL
          - EQUAL
          - EQUAL

      2:
        type: ORIENTATION_YAW
        value: 0.5
        operator: EQUAL