arm_name: KINOVA_GEN3_2_RIGHT

KINOVA_GEN3_2_RIGHT:
  gravitational_acceleration:
    - -9.5
    - -1.0
    - 1.1

  PRE_CONDITION:
    constraint_count: 1
    constraints:
      1:
        type: POSITION_XYZ
        value:
          - 0.5
          - NULL
          - NULL
        operator:
          - LESS_THAN
          - NULL
          - NULL

  PER_CONDITION:
    constraint_count: 2
    constraints:
      1:
        type: POSITION_XYZ
        value:
          - 0.8
          - NULL
          - NULL
        operator: 
          - EQUAL
          - NULL
          - NULL

      2:
        type: FORCE_XYZ
        value:
          - 5.0
          - NULL
          - NULL
        operator: 
          - EQUAL
          - NULL
          - NULL          


  POST_CONDITION:
    constraint_count: 1
    constraints:
      1:
        type: POSITION_XYZ
        value:
          - 0.8
          - NULL
          - NULL
        operator:
          - GREATER_THAN
          - NULL
          - NULL